[project]
name = "hello-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Šimon Plačko", email = "simon.placko6@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
hello-automation = "hello_automation:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
